# Generated by Django 4.0.2 on 2022-02-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getintouch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_post', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('sallery', models.ImageField(upload_to='photos/employee')),
                ('postedat', models.CharField(max_length=200)),
            ],
        ),
    ]
