# Generated by Django 4.0.2 on 2022-02-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getintouch', '0002_carrermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrermodel',
            name='sallery',
            field=models.CharField(max_length=200),
        ),
    ]
