# Generated by Django 4.0 on 2022-03-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getintouch', '0003_alter_carrermodel_sallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('another_phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('another_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
