# Generated by Django 4.0 on 2022-03-02 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fotterall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFromMd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotterall.boardof')),
            ],
        ),
    ]
