# Generated by Django 4.0 on 2022-03-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotterall', '0002_messagefrommd'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardof',
            name='postName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
