# Generated by Django 4.0.2 on 2022-02-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fromdata', '0003_alter_application_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to='resume/cv'),
        ),
    ]
