# Generated by Django 4.0.2 on 2022-02-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_gallerymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
