# Generated by Django 4.0.2 on 2022-02-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
